/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#1a1c1c",
        "on-primary-fixed-variant": "#474747",
        "surface-tint": "#5e5e5e",
        "surface": "#fbf9f9",
        "primary-fixed": "#e2e2e2",
        "tertiary": "#000000",
        "inverse-surface": "#303031",
        "secondary": "#aa361a",
        "on-surface-variant": "#4c4546",
        "secondary-fixed": "#ffdad2",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "surface-bright": "#fbf9f9",
        "primary-fixed-dim": "#c6c6c6",
        "outline": "#7e7576",
        "secondary-fixed-dim": "#ffb4a3",
        "surface-container-highest": "#e4e2e2",
        "surface-container-high": "#e9e8e7",
        "surface-variant": "#e4e2e2",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe7352",
        "background": "#fbf9f9",
        "inverse-primary": "#c6c6c6",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-dim": "#dbdad9",
        "on-secondary-fixed": "#3d0700",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f3",
        "on-secondary-container": "#6b1300",
        "outline-variant": "#cfc4c5",
        "on-primary-container": "#848484",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary": "#ffffff",
        "primary-container": "#1b1b1b",
        "surface-container": "#efeded",
        "on-secondary-fixed-variant": "#881f04",
        "on-error": "#ffffff",
        "on-tertiary-container": "#838484",
        "on-background": "#1b1c1c",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-surface": "#1b1c1c",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#1b1b1b",
        "inverse-on-surface": "#f2f0f0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem",
        "3xl": "1.5rem"
      },
      spacing: {
        "bento-gap": "1.5rem",
        "icon-size-md": "1.25rem",
        "section-margin": "2.5rem",
        "internal-padding": "1.5rem",
        "container-padding": "2rem"
      },
      fontFamily: {
        "sans": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "stat-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "display-md": ["Hanken Grotesk", "system-ui", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "stat-lg": ["20px", { "lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.5", "fontWeight": "500" }],
        "headline-lg": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "headline-lg-mobile": ["20px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-md": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }]
      },
      boxShadow: {
        'soft': '0 4px 40px -4px rgba(0, 0, 0, 0.05)',
        'float': '0 20px 40px -10px rgba(0, 0, 0, 0.08)',
      }
    },
  },
  plugins: [],
};
